# Generated by Django 2.1.3 on 2018-11-11 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AndroidNotificationDevices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=255)),
                ('version', models.CharField(choices=[('2.3', 'Gingerbread'), ('3.0', 'Honeycomb'), ('4.0', 'Ice Cream Sandwich'), ('4.1', 'Jelly Bean'), ('4.4', 'Kit Kat'), ('5.0', 'Lollipop'), ('6.0', 'Marshmallow'), ('7.0', 'Nougat'), ('8.0', 'Oreo'), ('9.0', 'Pie')], max_length=10)),
                ('registered_at', models.DateTimeField()),
                ('is_disabled', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='AppleNotificationDevices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=255)),
                ('version', models.IntegerField(choices=[(9, 'iOS9'), (10, 'iOS10'), (11, 'iOS11'), (12, 'iOS12')])),
                ('device', models.CharField(choices=[('se', 'iPhone SE'), ('6', 'iPhone 6'), ('6plus', 'iPhone 6 Plus'), ('7', 'iPhone 7'), ('7plus', 'iPhone 7 Plus'), ('8', 'iPhone 8'), ('8plus', 'iPhone 8 Plus'), ('x', 'iPhone X'), ('xr', 'iPhone XR'), ('xs', 'iPhone Xs'), ('xsm', 'iPhone Xs Max')], max_length=10)),
                ('registered_at', models.DateTimeField()),
                ('is_disabled', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='NotificationQueue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_token', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('message', models.CharField(max_length=255)),
            ],
        ),
    ]
