# Generated by Django 2.1.3 on 2018-11-11 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AndroidNotificationDevices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=255)),
                ('version', models.CharField(max_length=255)),
                ('device', models.CharField(max_length=255)),
                ('registered_at', models.DateTimeField()),
                ('is_disabled', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='AppleNotificationDevices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=255)),
                ('version', models.CharField(max_length=255)),
                ('device', models.CharField(max_length=255)),
                ('registered_at', models.DateTimeField()),
                ('is_disabled', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='NotificationQueue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_token', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('message', models.CharField(max_length=255)),
            ],
        ),
    ]
